/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinik;

import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
/**
 *
 * @author USER
 */
public class Kamar extends javax.swing.JFrame {
private Connection conn;
private DefaultTableModel tabmode;
    public Kamar() throws SQLException {
        this.conn = new koneksi().getkoneksi();
        initComponents();
        aktif();
        autonumber();
        datatable();
        
    }
    protected void aktif(){
        jenisKamar.setSelectedItem(null);
    }
    protected void kosong(){
        txtnama.setText("");
        txttarif.setText("");
        txtfasilitas.setText("");
    }
    protected void autonumber(){
        try{
            String sql = "SELECT kode_kamar FROM kamar order by kode_kamar asc";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            txtkode.setText("K0001");
            while(rs.next()){
                String id = rs.getString("kode_kamar").substring(2);
                int AN = Integer.parseInt(id)+1;
                String Nol ="";
                
                if(AN<10){
                    Nol = "000";
                }
                else if (AN<100){
                    Nol = "00";
                }
                else if (AN<1000){
                    Nol = "0";
                }
                else if(AN<10000){
                    Nol = "";
                }
                txtkode.setText("K"+Nol+AN);
            }
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "Auto number gagal"+e);
        }
    }
    protected void datatable(){
        Object[]Baris = { "Kode Kamar", "Jenis Kamar", "Nama Kamar", "Tarif", "Fasilitas"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcariitem.getText();
        
        try{
            String sql = "SELECT * FROM kamar where Jenis_Kamar like '%"+cariitem+"%' or Nama_Kamar like '%"+cariitem+"%' order by kode_kamar asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5)
                        });
            }
            TabelKamar.setModel(tabmode);
        }catch (SQLException e){
            JOptionPane.showMessageDialog(null,"data gagal dipanggil"+e);
            }
            
        }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        TabelKamar = new javax.swing.JTable();
        User = new javax.swing.JButton();
        Doktor = new javax.swing.JButton();
        Pasien = new javax.swing.JButton();
        Diagnosa = new javax.swing.JButton();
        Obat = new javax.swing.JButton();
        kamar = new javax.swing.JButton();
        Kasir = new javax.swing.JButton();
        Keluar = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        edit = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        txtkode = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jenisKamar = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        txtnama = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txttarif = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtfasilitas = new javax.swing.JTextField();
        txtcariitem = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cari = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        TabelKamar.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        TabelKamar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelKamarMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelKamar);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 70, 780, 150));

        User.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        User.setText("User");
        User.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserActionPerformed(evt);
            }
        });
        getContentPane().add(User, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 200, 40));

        Doktor.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Doktor.setText("Dokter");
        Doktor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DoktorActionPerformed(evt);
            }
        });
        getContentPane().add(Doktor, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 200, 40));

        Pasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Pasien.setText("Pasien");
        Pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasienActionPerformed(evt);
            }
        });
        getContentPane().add(Pasien, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, 200, 40));

        Diagnosa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Diagnosa.setText("Diagnosa");
        Diagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiagnosaActionPerformed(evt);
            }
        });
        getContentPane().add(Diagnosa, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 330, 200, 40));

        Obat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Obat.setText("Obat");
        Obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ObatActionPerformed(evt);
            }
        });
        getContentPane().add(Obat, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 200, 40));

        kamar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kamar.setText("Kamar");
        kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kamarActionPerformed(evt);
            }
        });
        getContentPane().add(kamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 410, 200, 40));

        Kasir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Kasir.setText("Kasir");
        Kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KasirActionPerformed(evt);
            }
        });
        getContentPane().add(Kasir, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 450, 200, 40));

        Keluar.setText("Keluar");
        Keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarActionPerformed(evt);
            }
        });
        getContentPane().add(Keluar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 510, -1, -1));

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        getContentPane().add(tambah, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 260, -1, -1));

        edit.setText("Edit");
        edit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editActionPerformed(evt);
            }
        });
        getContentPane().add(edit, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 260, -1, -1));

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        getContentPane().add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 260, -1, -1));

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        getContentPane().add(batal, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 260, -1, -1));
        getContentPane().add(txtkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 380, 230, -1));

        jLabel1.setText("Kode Kamar");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 380, -1, -1));

        jLabel2.setText("Jenis Kamar");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 440, -1, -1));

        jenisKamar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Kamar", "Ekonomi", "Suite", "VIP" }));
        getContentPane().add(jenisKamar, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 440, 230, -1));

        jLabel3.setText("Nama Kamar");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 500, -1, -1));
        getContentPane().add(txtnama, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 500, 230, -1));

        jLabel4.setText("Fasilitas");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 470, -1, -1));

        txttarif.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txttarifKeyTyped(evt);
            }
        });
        getContentPane().add(txttarif, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 410, 210, -1));

        jLabel5.setText("Tarif");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 410, -1, -1));
        getContentPane().add(txtfasilitas, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 470, 210, -1));

        txtcariitem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariitemActionPerformed(evt);
            }
        });
        getContentPane().add(txtcariitem, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 300, 210, -1));

        jLabel8.setText("Kategori");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 250, -1, -1));

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        getContentPane().add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 300, -1, -1));

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori", "Jenis Kamar", "Nama Kamar" }));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 250, 210, -1));

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FiksHome.png"))); // NOI18N
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -70, 1200, 740));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void UserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserActionPerformed
        User frmU = null;
        try{
            frmU = new User();
        }
        catch (SQLException ex){
            Logger.getLogger(Kamar.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_UserActionPerformed

    private void PasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasienActionPerformed
        Pasien frmP = null;
        try {
            frmP = new Pasien();
        } catch (SQLException ex) {
            Logger.getLogger(Kamar.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmP.setVisible(true); 
    }//GEN-LAST:event_PasienActionPerformed

    private void DoktorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DoktorActionPerformed
        Dokter frmD = null;
        try {
            frmD = new Dokter();
        } catch (SQLException ex) {
            Logger.getLogger(Dokter.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmD.setVisible(true);
    }//GEN-LAST:event_DoktorActionPerformed

    private void DiagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiagnosaActionPerformed
        Diagnosa frmDi = null;
        try {
            frmDi = new Diagnosa();
        } catch (SQLException ex) {
            Logger.getLogger(Kamar.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmDi.setVisible(true);
    }//GEN-LAST:event_DiagnosaActionPerformed

    private void KasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KasirActionPerformed
        Kasir frmK = null;
    try {
        frmK = new Kasir();
    } catch (SQLException ex) {
        Logger.getLogger(Kamar.class.getName()).log(Level.SEVERE, null, ex);
    }
        frmK.setVisible(true);
    }//GEN-LAST:event_KasirActionPerformed

    private void kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kamarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kamarActionPerformed

    private void ObatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ObatActionPerformed
        Obat frmO = null;
        try {
            frmO = new Obat();
        } catch (SQLException ex) {
            Logger.getLogger(Kamar.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmO.setVisible(true);
    }//GEN-LAST:event_ObatActionPerformed

    private void KeluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarActionPerformed
        int dialogBtn =JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Akan Keluar?", "Peringatan", dialogBtn);
        if (dialogResult == 0){
            Login frmU = null;
        frmU = new Login();
        frmU.setVisible(true);
        this.dispose();
        }else{
        }
    }//GEN-LAST:event_KeluarActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
        String sql = "insert into kamar values (?,?,?,?,?)";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1, txtkode.getText());
            stat.setString(2, jenisKamar.getSelectedItem().toString());
            stat.setString(3, txtnama.getText());
            stat.setString(4, txttarif.getText());
            stat.setString(5, txtfasilitas.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
        }
        catch(SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan"+e);
        }
        datatable();
    
        
    }//GEN-LAST:event_tambahActionPerformed

    private void txtcariitemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariitemActionPerformed
        if (evt.hashCode()== KeyEvent.VK_ENTER){
            datatable();
        }
    }//GEN-LAST:event_txtcariitemActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        jenisKamar.getSelectedItem().toString();
        txtnama.getText();
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void TabelKamarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelKamarMouseClicked
        int bar = TabelKamar.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        
        txtkode.setText(a);
        jenisKamar.setSelectedItem(b);
        txtnama.setText(c);
        txttarif.setText(d);
        txtfasilitas.setText(e);
        
    }//GEN-LAST:event_TabelKamarMouseClicked

    private void editActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editActionPerformed
        String sql = "UPDATE kamar set kode_kamar=?, jenis_kamar=?, nama_kamar=?, tarif=?, fasilitas=? where kode_kamar='" +txtkode.getText()+"'";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,txtkode.getText());
            stat.setString(2,jenisKamar.getSelectedItem().toString());
            stat.setString(3,txtnama.getText());
            stat.setString(4,txttarif.getText());
            stat.setString(5, txtfasilitas.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog (null, "data berhasil diubah");
            kosong();
            
        }
        catch (SQLException e){
            JOptionPane.showMessageDialog (null, "data gagal diubah" +e);
        }
        datatable();
    }//GEN-LAST:event_editActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null, "hapus", "konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        String sql = "delete from kamar where kode_kamar = '"+txtkode.getText()+"'";
        try{
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil dihapus");
            kosong();
        }
        catch(SQLException e){
          JOptionPane.showMessageDialog(null, "data gagal dihapus" +e);
            }
            datatable();  
        
    }//GEN-LAST:event_hapusActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        kosong();
        aktif();
        autonumber();
        datatable();
    }//GEN-LAST:event_batalActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        datatable();
    }//GEN-LAST:event_cariActionPerformed

    private void txttarifKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txttarifKeyTyped
        char[] x = new char[] {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',',','.'};
        boolean boleh = false;
        for (int i=0; i < x.length; i++) {
        if (x[i] == evt.getKeyChar()) {
        boleh = true;
            break;
            }
            }
        if (!boleh) {
        evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_txttarifKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kamar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Kamar().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Kamar.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Diagnosa;
    private javax.swing.JButton Doktor;
    private javax.swing.JButton Kasir;
    private javax.swing.JButton Keluar;
    private javax.swing.JButton Obat;
    private javax.swing.JButton Pasien;
    private javax.swing.JTable TabelKamar;
    private javax.swing.JButton User;
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JButton edit;
    private javax.swing.JButton hapus;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox<String> jenisKamar;
    private javax.swing.JButton kamar;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtcariitem;
    private javax.swing.JTextField txtfasilitas;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtnama;
    private javax.swing.JTextField txttarif;
    // End of variables declaration//GEN-END:variables
}
