/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package klinik;

import java.awt.event.KeyEvent;
import java.io.File;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.HashMap;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.util.JRLoader;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author USER
 */
public class Obat extends javax.swing.JFrame {
    private Connection conn;
    private DefaultTableModel tabmode;
    /**
     * Creates new form Obat
     */
    public Obat() throws SQLException {
        this.conn = new koneksi().getkoneksi();
        initComponents();
        aktif();
        autonumber();
        datatable();
        Date now;
        now = new Date();

        SimpleDateFormat tgl1,tgl2;
        tgl1 = new SimpleDateFormat("EEEE, dd MMM yyyy");
        tgl2 = new SimpleDateFormat("HH:mm:ss");

        Tanggal.setText(tgl1.format(now));
        Waktu.setText(tgl2.format(now));
    
    }
    
    protected void aktif(){
        kategoriobat.setSelectedItem(null);
        kategorijenis.setSelectedItem(null);
    }
    
    protected void kosong(){
        txtkode.setText("");
        txtmasuk.setText("");
        txtexp.setText("");
        txtobat.setText("");
        txtmerek.setText("");
        txtbeli.setText("");
        txtjual.setText("");
        txtjumlah.setText("");
        txtexp.setText("");
        txtmasuk.setText("");
        txtcari.setText("");
        kategoriobat.setSelectedItem(null);
        kategorijenis.setSelectedItem(null);
    }
    
protected void autonumber(){
        try{
            String sql = "SELECT kode_obat FROM obat order by kode_obat asc";
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);
            txtkode.setText("SF01");
            while(rs.next()){
                String id = rs.getString("kode_obat").substring(2);
                int AN = Integer.parseInt(id)+1;
                String Nol = "";
                
                if (AN < 10){
                    Nol = "0";
                }
                else if (AN < 100){
                    Nol = "";
                }
                txtkode.setText("SF"+Nol+AN);
            }
        }
            catch(SQLException e){
                    JOptionPane.showMessageDialog(null, "Auto number gagal"+e);
            }
    }
protected void datatable(){
        Object[] Baris = {"Kode Obat","Nama Obat","Kategori Obat","Jenis Obat","Merek Obat","Harga Beli","Harga Jual","Jumlah","Tgl Masuk","Tgl Kadaluarsa"};
        tabmode = new DefaultTableModel(null, Baris);
        String cariitem = txtcari.getText();

        try {
            String sql = "SELECT * FROM obat where jenis_obat like '%"+cariitem+"%' or kategori_obat like '%"+cariitem+"%' or nama_obat like '%"+cariitem+"%' order by kode_obat asc";
            Statement stat = conn.createStatement();
            ResultSet hasil = stat.executeQuery(sql);
            while (hasil.next()){
                tabmode.addRow(new Object[]{
                hasil.getString(1),
                hasil.getString(2),
                hasil.getString(3),
                hasil.getString(4),
                hasil.getString(5),
                hasil.getString(6),
                hasil.getString(7),
                hasil.getString(8),
                hasil.getString(9),
                hasil.getString(10)
            });
        }
        tabelobat.setModel(tabmode);
     } catch (SQLException e){
            JOptionPane.showMessageDialog(null,"data gagal dipanggil"+e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Tanggal = new javax.swing.JLabel();
        Waktu = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelobat = new javax.swing.JTable();
        user = new javax.swing.JButton();
        pasien = new javax.swing.JButton();
        dokter = new javax.swing.JButton();
        diagnosa = new javax.swing.JButton();
        obat = new javax.swing.JButton();
        kasir = new javax.swing.JButton();
        keluar = new javax.swing.JButton();
        tambah = new javax.swing.JButton();
        ubah = new javax.swing.JButton();
        hapus = new javax.swing.JButton();
        cetak = new javax.swing.JButton();
        batal = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        cari = new javax.swing.JButton();
        kamar = new javax.swing.JButton();
        kategori = new javax.swing.JComboBox<>();
        txtcari = new javax.swing.JTextField();
        txtkode = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtobat = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        kategoriobat = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        kategorijenis = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        txtmerek = new javax.swing.JTextField();
        txtbeli = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtjual = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtjumlah = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        txtmasuk = new javax.swing.JTextField();
        txtexp = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 771));
        jPanel1.setLayout(null);

        Tanggal.setText("jLabel1");
        jPanel1.add(Tanggal);
        Tanggal.setBounds(230, 50, 51, 20);

        Waktu.setText("jLabel1");
        jPanel1.add(Waktu);
        Waktu.setBounds(230, 80, 51, 20);

        tabelobat.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabelobat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelobatMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelobat);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(350, 70, 780, 156);

        user.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        user.setText("User");
        user.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userActionPerformed(evt);
            }
        });
        jPanel1.add(user);
        user.setBounds(50, 180, 220, 40);

        pasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        pasien.setText("Pasien");
        pasien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pasienActionPerformed(evt);
            }
        });
        jPanel1.add(pasien);
        pasien.setBounds(50, 280, 220, 40);

        dokter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        dokter.setText("Dokter");
        dokter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dokterActionPerformed(evt);
            }
        });
        jPanel1.add(dokter);
        dokter.setBounds(50, 230, 220, 40);

        diagnosa.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        diagnosa.setText("Diagnosa");
        diagnosa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                diagnosaActionPerformed(evt);
            }
        });
        jPanel1.add(diagnosa);
        diagnosa.setBounds(50, 330, 220, 40);

        obat.setBackground(new java.awt.Color(51, 51, 255));
        obat.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        obat.setText("Obat");
        obat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                obatActionPerformed(evt);
            }
        });
        jPanel1.add(obat);
        obat.setBounds(50, 380, 220, 40);

        kasir.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kasir.setText("Kasir");
        kasir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kasirActionPerformed(evt);
            }
        });
        jPanel1.add(kasir);
        kasir.setBounds(50, 480, 220, 40);

        keluar.setBackground(new java.awt.Color(51, 51, 255));
        keluar.setText("Keluar");
        keluar.setBorderPainted(false);
        keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keluarActionPerformed(evt);
            }
        });
        jPanel1.add(keluar);
        keluar.setBounds(110, 530, 90, 30);

        tambah.setText("Tambah");
        tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tambahActionPerformed(evt);
            }
        });
        jPanel1.add(tambah);
        tambah.setBounds(340, 250, 91, 29);

        ubah.setText("Edit");
        ubah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubahActionPerformed(evt);
            }
        });
        jPanel1.add(ubah);
        ubah.setBounds(450, 250, 59, 29);

        hapus.setText("Hapus");
        hapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapusActionPerformed(evt);
            }
        });
        jPanel1.add(hapus);
        hapus.setBounds(530, 250, 77, 29);

        cetak.setText("Cetak");
        cetak.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cetakActionPerformed(evt);
            }
        });
        jPanel1.add(cetak);
        cetak.setBounds(620, 250, 71, 29);

        batal.setText("Batal");
        batal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batalActionPerformed(evt);
            }
        });
        jPanel1.add(batal);
        batal.setBounds(710, 250, 67, 29);

        jLabel1.setForeground(new java.awt.Color(240, 240, 240));
        jLabel1.setText("Kategori");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(870, 250, 58, 20);

        cari.setText("Cari");
        cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cariActionPerformed(evt);
            }
        });
        jPanel1.add(cari);
        cari.setBounds(870, 280, 61, 29);

        kamar.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        kamar.setText("Kamar");
        kamar.setToolTipText("");
        kamar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kamarActionPerformed(evt);
            }
        });
        jPanel1.add(kamar);
        kamar.setBounds(50, 430, 220, 40);

        kategori.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori", "Jenis Obat", "Kategori Obat", "Kode Obat" }));
        kategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategoriActionPerformed(evt);
            }
        });
        jPanel1.add(kategori);
        kategori.setBounds(950, 250, 180, 26);

        txtcari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtcariActionPerformed(evt);
            }
        });
        jPanel1.add(txtcari);
        txtcari.setBounds(950, 290, 180, 26);
        jPanel1.add(txtkode);
        txtkode.setBounds(480, 350, 220, 26);

        jLabel2.setText("Kode Obat");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(350, 350, 80, 20);
        jPanel1.add(txtobat);
        txtobat.setBounds(480, 390, 220, 26);

        jLabel3.setText("Nama Obat");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(350, 390, 80, 20);

        kategoriobat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kategori", "Obat Dalam", "Obat Luar", " " }));
        jPanel1.add(kategoriobat);
        kategoriobat.setBounds(480, 430, 220, 26);

        jLabel5.setText("Jenis Obat");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(350, 470, 74, 20);

        jLabel4.setText("Kategori Obat");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(350, 430, 97, 20);

        kategorijenis.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Jenis Obat", "Botol", "Kaplet", "Kapsul", "Pil", "Salep", "Sirup" }));
        jPanel1.add(kategorijenis);
        kategorijenis.setBounds(480, 470, 220, 26);

        jLabel6.setText("Merek Obat ");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(350, 520, 86, 20);
        jPanel1.add(txtmerek);
        txtmerek.setBounds(480, 510, 220, 26);

        txtbeli.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtbeliKeyTyped(evt);
            }
        });
        jPanel1.add(txtbeli);
        txtbeli.setBounds(890, 350, 230, 26);

        jLabel7.setText("Harga Beli");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(780, 350, 72, 20);

        jLabel8.setText("Harga Jual");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(780, 390, 75, 20);

        txtjual.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtjualActionPerformed(evt);
            }
        });
        txtjual.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjualKeyTyped(evt);
            }
        });
        jPanel1.add(txtjual);
        txtjual.setBounds(890, 390, 230, 26);

        jLabel9.setText("Qty");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(780, 430, 25, 20);

        txtjumlah.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtjumlahKeyTyped(evt);
            }
        });
        jPanel1.add(txtjumlah);
        txtjumlah.setBounds(890, 430, 230, 26);

        jLabel11.setText("Tanggal Masuk");
        jPanel1.add(jLabel11);
        jLabel11.setBounds(780, 510, 106, 20);
        jPanel1.add(txtmasuk);
        txtmasuk.setBounds(890, 510, 230, 26);
        jPanel1.add(txtexp);
        txtexp.setBounds(890, 470, 230, 26);

        jLabel10.setText("Tanggal EXP");
        jPanel1.add(jLabel10);
        jLabel10.setBounds(780, 470, 89, 20);

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/FiksHome.png"))); // NOI18N
        jPanel1.add(jLabel13);
        jLabel13.setBounds(0, -140, 1200, 880);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1199, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 606, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 1, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keluarActionPerformed
         int dialogBtn =JOptionPane.YES_NO_OPTION;
        int dialogResult = JOptionPane.showConfirmDialog(this, "Anda Yakin Akan Keluar?", "Peringatan", dialogBtn);
        if (dialogResult == 0){
            Login frmU = null;
        frmU = new Login();
        frmU.setVisible(true);
        this.dispose();
        }else{
        }
    }//GEN-LAST:event_keluarActionPerformed

    private void tambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tambahActionPerformed
         String sql = "insert into obat values (?,?,?,?,?,?,?,?,?,?)";
       
       try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,txtkode.getText());
            stat.setString(2,txtobat.getText());
            stat.setString(3,kategoriobat.getSelectedItem().toString());
            stat.setString(4,kategorijenis.getSelectedItem().toString());
            stat.setString(5,txtmerek.getText());
            stat.setString(6,txtbeli.getText());
            stat.setString(7,txtjual.getText());
            stat.setString(8,txtjumlah.getText());
            stat.setString(9,txtmasuk.getText());
            stat.setString(10,txtexp.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil disimpan");
            kosong();
       }
       catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal disimpan" +e);
       }
       datatable();
    
    }//GEN-LAST:event_tambahActionPerformed

    private void cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cariActionPerformed
        datatable();
    }//GEN-LAST:event_cariActionPerformed

    private void txtcariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtcariActionPerformed
        if (evt.hashCode()== KeyEvent.VK_ENTER){
        datatable();
        }
    }//GEN-LAST:event_txtcariActionPerformed

    private void kategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategoriActionPerformed
       kategorijenis.getSelectedItem().toString();
        kategoriobat.getSelectedItem().toString();
        txtkode.getText();
    }//GEN-LAST:event_kategoriActionPerformed

    private void tabelobatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelobatMouseClicked
        int bar = tabelobat.getSelectedRow();
        String a = tabmode.getValueAt(bar, 0).toString();
        String b = tabmode.getValueAt(bar, 1).toString();
        String c = tabmode.getValueAt(bar, 2).toString();
        String d = tabmode.getValueAt(bar, 3).toString();
        String e = tabmode.getValueAt(bar, 4).toString();
        String f = tabmode.getValueAt(bar, 5).toString();
        String g = tabmode.getValueAt(bar, 6).toString();
        String h = tabmode.getValueAt(bar, 7).toString();
        String i = tabmode.getValueAt(bar, 8).toString();
        String j = tabmode.getValueAt(bar, 9).toString();
    
        txtkode.setText(a);
        txtobat.setText(b);
        kategoriobat.setSelectedItem(c);
        kategorijenis.setSelectedItem(d);
        txtmerek.setText(e);
        txtbeli.setText(f);
        txtjual.setText(g);
        txtjumlah.setText(h);
        txtmasuk.setText(i);
        txtexp.setText(j);
    }//GEN-LAST:event_tabelobatMouseClicked

    private void ubahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubahActionPerformed
        String sql = "update obat set kode_obat=?, nama_obat=?, kategori_obat=?, jenis_obat=?, merek_obat=?, harga_beli_obat=?, harga_jual_obat=?, jumlah_obat=?, tanggal_masuk=?, expired=? where kode_obat='"+txtkode.getText()+"'";
       
       try {
            PreparedStatement stat = conn.prepareStatement(sql);
            stat.setString(1,txtkode.getText());
            stat.setString(2,txtobat.getText());
            stat.setString(3,kategoriobat.getSelectedItem().toString());
            stat.setString(4,kategorijenis.getSelectedItem().toString());
            stat.setString(5,txtmerek.getText());
            stat.setString(6,txtbeli.getText());
            stat.setString(7,txtjual.getText());
            stat.setString(8,txtjumlah.getText());
            stat.setString(9,txtmasuk.getText());
            stat.setString(10,txtexp.getText());
            
            stat.executeUpdate();
            JOptionPane.showMessageDialog(null, "data berhasil diubah");
            kosong();
       }
       catch (SQLException e){
            JOptionPane.showMessageDialog(null, "data gagal diubah" +e);
       }
       datatable();
    }//GEN-LAST:event_ubahActionPerformed

    private void hapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapusActionPerformed
        int ok = JOptionPane.showConfirmDialog(null,"hapus","konfirmasi dialog", JOptionPane.YES_NO_OPTION);
        String sql = "delete from obat where kode_obat = '"+txtkode.getText()+"'";
            try {
                PreparedStatement stat = conn.prepareStatement(sql);
                stat.executeUpdate();
                JOptionPane.showMessageDialog(null, "data berhasil dihapus");
                kosong();
            }
            catch (SQLException e){
                JOptionPane.showMessageDialog(null, "data gagal dihapus" +e);
            }
            datatable();
    }//GEN-LAST:event_hapusActionPerformed

    private void userActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userActionPerformed
        User frmU = null;
        try {
            frmU = new User();
        } catch (SQLException ex) {
            Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmU.setVisible(true);
    }//GEN-LAST:event_userActionPerformed

    private void pasienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pasienActionPerformed
         Pasien frmP = null;
        try {
            frmP = new Pasien();
        } catch (SQLException ex) {
            Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmP.setVisible(true);
    }//GEN-LAST:event_pasienActionPerformed

    private void dokterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dokterActionPerformed
        Dokter frmD = null;
        try {
            frmD = new Dokter();
        } catch (SQLException ex) {
            Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmD.setVisible(true);
    }//GEN-LAST:event_dokterActionPerformed

    private void diagnosaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_diagnosaActionPerformed
        Diagnosa frmDi = null;
        try {
            frmDi = new Diagnosa();
        } catch (SQLException ex) {
            Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmDi.setVisible(true);
    }//GEN-LAST:event_diagnosaActionPerformed

    private void obatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_obatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_obatActionPerformed

    private void kasirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kasirActionPerformed
        Kasir frmK = null;
        try {
            frmK = new Kasir();
        } catch (SQLException ex) {
            Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmK.setVisible(true);
    }//GEN-LAST:event_kasirActionPerformed

    private void cetakActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cetakActionPerformed
        try{
            HashMap parameter = new HashMap();
            parameter.put("id_pasien",txtkode.getText());
            File file = new File ("src/Report/Obat.jasper");
            JasperReport jr = (JasperReport) JRLoader.loadObject(file);
            JasperPrint jp = JasperFillManager.fillReport(jr, parameter, conn);
            JasperViewer.viewReport(jp, false);
            JasperViewer.setDefaultLookAndFeelDecorated(true);
        } catch (Exception e){
            javax.swing.JOptionPane.showMessageDialog(null,
                    "Data Tidak Dapat di Cetak !!!" + "\n" + e.getMessage(), 
                    "Cetak Data", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_cetakActionPerformed

    private void batalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batalActionPerformed
        kosong();
        aktif();
        autonumber();
        datatable();
    }//GEN-LAST:event_batalActionPerformed

    private void kamarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kamarActionPerformed
        Kamar frmK = null;
        try {
            frmK = new Kamar();
        } catch (SQLException ex) {
            Logger.getLogger(Kamar.class.getName()).log(Level.SEVERE, null, ex);
        }
        frmK.setVisible(true);
    }//GEN-LAST:event_kamarActionPerformed

    private void txtbeliKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtbeliKeyTyped
        char[] x = new char[] {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',',','.'};
        boolean boleh = false;
        for (int i=0; i < x.length; i++) {
        if (x[i] == evt.getKeyChar()) {
        boleh = true;
            break;
            }
            }
        if (!boleh) {
        evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_txtbeliKeyTyped

    private void txtjualActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtjualActionPerformed
        
    }//GEN-LAST:event_txtjualActionPerformed

    private void txtjualKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjualKeyTyped
        char[] x = new char[] {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',',','.'};
        boolean boleh = false;
        for (int i=0; i < x.length; i++) {
        if (x[i] == evt.getKeyChar()) {
        boleh = true;
            break;
            }
            }
        if (!boleh) {
        evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_txtjualKeyTyped

    private void txtjumlahKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtjumlahKeyTyped
        char[] x = new char[] {'0', '1', '2', '3', '4', '5', '6', '7', '8', '9',',','.'};
        boolean boleh = false;
        for (int i=0; i < x.length; i++) {
        if (x[i] == evt.getKeyChar()) {
        boleh = true;
            break;
            }
            }
        if (!boleh) {
        evt.setKeyChar((char) 0);
        }
    }//GEN-LAST:event_txtjumlahKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Obat.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Obat().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Obat.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Tanggal;
    private javax.swing.JLabel Waktu;
    private javax.swing.JButton batal;
    private javax.swing.JButton cari;
    private javax.swing.JButton cetak;
    private javax.swing.JButton diagnosa;
    private javax.swing.JButton dokter;
    private javax.swing.JButton hapus;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton kamar;
    private javax.swing.JButton kasir;
    private javax.swing.JComboBox<String> kategori;
    private javax.swing.JComboBox<String> kategorijenis;
    private javax.swing.JComboBox<String> kategoriobat;
    private javax.swing.JButton keluar;
    private javax.swing.JButton obat;
    private javax.swing.JButton pasien;
    private javax.swing.JTable tabelobat;
    private javax.swing.JButton tambah;
    private javax.swing.JTextField txtbeli;
    private javax.swing.JTextField txtcari;
    private javax.swing.JTextField txtexp;
    private javax.swing.JTextField txtjual;
    private javax.swing.JTextField txtjumlah;
    private javax.swing.JTextField txtkode;
    private javax.swing.JTextField txtmasuk;
    private javax.swing.JTextField txtmerek;
    private javax.swing.JTextField txtobat;
    private javax.swing.JButton ubah;
    private javax.swing.JButton user;
    // End of variables declaration//GEN-END:variables
}
